// Generated by Wrangler by running `wrangler types`

interface Env {
	RELAY: DurableObjectNamespace<import("./src/index").Relay>;
}
declare module "*.html" {
	const value: string;
	export default value;
}